119 136 137 update get started
atorus-research/logrx pull request #144
Opened 2022-11-15 15:47 UTC by thomasp-b

### Thank you for your Pull Request! 

We have developed a Pull Request template to aid you and our reviewers.  Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the logrx codebase remains robust and consistent.  

### The spirit of logrx

While many packages to facilitate the logging of code already exist in the R ecosystem, it is hard to find a solution that works well for clinical programming applications. Many logging implementations are more implicit and rely on user input to create the log for the execution of a script. While this is useful for logging specific events of an application, in clinical programming a log has a set purpose.

logrx is built around the concept of creating a log for the execution of an R script that provides an overview of what happened as well as the environment that it happened in. We set out to create a flexible logging utility that could provide the necessary information to anyone reviewing the code execution so they can recreate the execution environment and run the code for themselves. Please make sure your Pull Request meets this **spirit of logrx**.

Please check off each taskbox as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `dev` branch until you have checked off each task.

- [x] The spirit of logrx is met in your Pull Request
- [x] Check that your Pull Request is targeting the dev branch, Pull Requests to master should use the [Release Pull Request Template](https://github.com/atorus-research/logrx/blob/main/.github/PULL_REQUEST_TEMPLATE/release.md)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests
- [x] Creation/updates to relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Update NEWS.md if the changes pertain to a user-facing function (i.e. it has an @export tag) or documentation aimed at users (rather than developers)
- [x] Address any updates needed for vignettes and/or templates
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

2022-11-15 16:13 UTC, bms63 commented on vignettes/logrx.Rmd
>  * `hash_sum`:  A unique sha1 is created for the log file
```suggestion
* `hash_sum`:  A unique hashsum is created for the log file
```

2022-11-15 16:14 UTC, bms63 commented on vignettes/logrx.Rmd
> +* `metadata`: logrx `package` information
```suggestion
* `metadata`: `logrx` package information
```

2022-11-15 16:15 UTC, bms63 commented on vignettes/logrx.Rmd
>  * `hash_sum`:  A unique sha1 is created for the log file
The hash_sum should go under the `user and file info` section.  We also need a new log rendered for the screenshot that has the `File HashSum:` section in it

2022-11-15 16:19 UTC, bms63 requested changes
![image](https://user-images.githubusercontent.com/10111024/201970832-c8210990-40f1-46ca-8bc7-fb46930cf662.png)

Can we get rid of that according ??

Can we put in a section for running with the addin as well?

2022-11-29 19:58 UTC, kodesiba commented
@bms63 I wanted to check if you had other feedback.  If you're done then @thomasp-b if you have time to knock out the few changes left we can get this through

2022-11-30 08:24 UTC, thomasp-b commented
> @bms63 I wanted to check if you had other feedback. If you're done then @thomasp-b if you have time to knock out the few changes left we can get this through

I'll work on what needs to be finalised tomorrow before our catch-up.

2022-12-07 21:09 UTC, kodesiba commented
@thomasp-b checking in on the status of this, I can pick up the rest of the docs once this is done.

2022-12-08 23:25 UTC, bms63 approved these changes
LGTM!

2022-12-13 14:30 UTC, kodesiba commented
@bms63 looking at the merge conflict and it looks like in #138 we removed the adsl.R file and I think added it to the tidylog examples.  Do you have time to reconcile these and make sure we have the whole data-raw folder updated so it's consistent with what we have in the dev branch?

2022-12-15 22:23 UTC, merged